openapi: 3.0.3
info:
  title: Training hub
  description: ''
  version: 1.0.11
tags:
  - name: Post
    description: ''
paths:
  /post:
    post:
      tags:
        - Post
      description: upload a post as a user
      operationId: uploadPost
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostRequest'
      responses:
        '201':
          description: Created succesfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostResponse'
        '400':
          description: Bad response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Invalid
  /post/{postId}:
    put:
      description: update a post as a user
      operationId: updatePost
      tags:
        - Post
      parameters:
        - in: path
          name: postId
          required: true
          description: id of the post to be updated
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostResponse'
      responses:
        '202':
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostResponse'
        '404':
          description: Accepted
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Not Found
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Bad Request
components:
  schemas:
    PostRequest:
      type: object
      properties:
        title:
          type: string
          example: Spring boot
        description:
          type: string
          example: important in backend team
        tag:
          type: array
          items:
            $ref: '#/components/schemas/Tag'
        attachment:
          type: array
          items:
            $ref: '#/components/schemas/Attachment'
    PostResponse:
      type: object
      properties:
        postId:
          type: string
        title:
          type: string
          example: Springboot
        description:
          type: string
          example: important in backend team
        tag:
          type: array
          items:
            $ref: '#/components/schemas/Tag'
        attachment:
          type: array
          items:
            $ref: '#/components/schemas/Attachment'
    Attachment:
      type: object
      properties:
        attachment:
          type: string
    Tag:
      type: object
      properties:
        tagName:
          type: string