openapi: 3.0.3
info:
  title: Training hub
  description: |-
  version: 1.0.11

tags:
  - name:   Post
    description: |-

paths:
  /post:
    post:
      tags:
        - Post
      description: upload a post as a user
      operationId: UploadPost
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostRequest'

      responses:
        '201':
          description: Created succesfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadResponse'

        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadResponse'

components:
  schemas:
    PostRequest :
      type: object
      properties:
        title:
          type: string
          example : "Spring boot"
        description:
          type: string
          example: "important in backend team"
        tag:
          type: array
          items:
            type: string
          minItems: 1
        Attachment:
          $ref: '#/components/schemas/Attachment'
        User:
          $ref: '#/components/schemas/UserResponse'

    PostResponse :
      type: object
      properties:
        userId :
          type: string
        rating:
          type: integer
        title:
          type: string
          example : Springboot
        description:
          type: string
          example: important in backend team
        tag:
          type: array
          items:
            type: string
          minItems: 1
        Attachment:
          $ref: '#/components/schemas/Attachment'
        User:
          $ref: '#/components/schemas/UserResponse'

    Attachment:
      type: object
      properties :
        attachment:
          type: string

    UserResponse:
      type: object
      properties :
        UserId:
          type: integer
        email :
          type: string
        firstName :
          type : string
        lastName:
          type : string
        role:
          $ref: "#/components/schemas/Role"

    Role:
      type: object
      properties:
        role:
          type: string

    BadResponse:
      type: object
      properties:
        StatusCode:
          type: integer
        message:
          type: string