<<<<<<< HEAD
openapi: 3.0.3
info:
  title: Training hub
  description: |-
    
 

  version: 1.0.11

tags:
  - name:   Post
    description: |-

paths:
  /post:
    post:
      tags:
        - Post
      description: upload a post as a user
      operationId: UploadPost
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostRequest'

      responses:
        '201':
          description: Created succesfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostResponse'
        '400':
          description: Bad response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message :
                    type: string
                    example : Invalid

components:
  schemas:
    PostRequest :
      type: object
      properties:
        rating:
          type: integer
          example: 4
        title:
          type: string
          example : "Spring boot"
        description:
          type: string
          example: "important in backend team"
        tag:
          type: array
          items:
            type: string
          minItems: 1
        Attachment:
          $ref: '#/components/schemas/Attachment'
        User:
          $ref: '#/components/schemas/UserResponse'

    PostResponse :
      type: object
      properties:
        postId :
          type: integer
        rating:
          type: integer
        title:
          type: string
          example : Springboot
        description:
          type: string
          example: important in backend team
        tag:
          type: array
          items:
            type: string
          minItems: 1
        Attachment:
          $ref: '#/components/schemas/Attachment'
        User:
          $ref: '#/components/schemas/UserResponse'

    Attachment:
      type: object
      properties :
        attachment:
          type: string

    UserResponse:
      type: object
      properties :
        userId:
          type: integer
        email :
          type: string
        firstName :
          type : string
        lastName:
          type : string
        role:
          $ref: "#/components/schemas/Role"

    Role:
      type: object
      properties:
        role:
          type: string
=======
openapi: 3.0.3
info:
  title: Training hub
  description: |-
    
 

  version: 1.0.11

tags:
  - name:   Post
    description: |-

paths:
  /post:
    post:
        tags:
          - Post
        description: upload a post as a user
        operationId: UploadPost
        requestBody:

          required: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'







        responses:
          '201':
            description: Created succesfully
            content:
              application/json:
                schema:



          '400':
            description: Bad response
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    message :
                      type: string
                      example : Invalid

        security:
          - petstore_auth:
              - write:pets
              - read:pets
components:
  schemas:
    Post :
      type: object
      properties:



        title:
          type: string
          example : Springboot

        description:
          type: string
          example: important in backend team
        tags:
          type: array
          items:
            type: string
          minItems: 1
        content:
          type: array
          items:
            type: string
            name:



>>>>>>> origin/feature/FT01-testing
